#!/bin/bash

if [ "$#" = "0" ] ; then
    echo "No arguments passed."
    exit 1
fi

for argument in "$@" ; do
    gcc -Wall -Werror -Wextra -pedantic -std=gnu89 "$argument" "mains/${argument%-*}-main.c" -o test && ./test && rm test \
    && /d/Projects/alx/printf_project/Betty/betty "$argument"
done
